version: '3.4'

services:
  scrumpoker:
    image: ${DOCKER_REGISTRY-}scrumpoker
    ports:
    - 8080:80
    build:
      context: .
      dockerfile: ScrumPoker/Dockerfile
    restart: always
  redis:
    image: redis
    ports:
    - 6379:6379
    restart: always